from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field

from ai.schemas.weather import DailyForecast, TripRisk


class ItineraryItem(BaseModel):
    time: str = Field(min_length=1)
    title: str = Field(min_length=1)
    description: str = Field(min_length=1)
    type: Literal["activity", "meal", "transport", "stay"]


class ItineraryDay(BaseModel):
    day: int = Field(ge=1)
    date: str | None = None
    title: str = Field(min_length=1)
    items: list[ItineraryItem] = Field(default_factory=list)


class BudgetBreakdown(BaseModel):
    flights: float = Field(ge=0)
    stay: float = Field(ge=0)
    activities: float = Field(ge=0)
    food: float = Field(ge=0)
    total: float = Field(ge=0)
    currency: str = Field(min_length=1, max_length=8)


class WeatherNotes(BaseModel):
    summary: str = Field(min_length=1)
    confidence: Literal["low", "medium", "high"] = "medium"


class TravelPlanLLMOutput(BaseModel):
    """What the LLM generates — all required, no server-side defaults."""
    destination: str = Field(min_length=1)
    days: int = Field(ge=1, le=30)
    travelers: int = Field(default=1, ge=1, le=20)
    summary: str = Field(min_length=1)
    itinerary: list[ItineraryDay]
    budget: BudgetBreakdown
    cover_emoji: str = Field(default="✈️")
    verification_tips: list[str] = Field(default_factory=list)


class TravelAgentStructuredResponse(BaseModel):
    # ── LLM-generated fields ──────────────────────────────────────────────────
    destination: str = Field(min_length=1)
    days: int = Field(ge=1, le=30)
    travelers: int = Field(default=1, ge=1, le=20)
    summary: str = Field(min_length=1)
    itinerary: list[ItineraryDay] = Field(default_factory=list)
    budget: BudgetBreakdown = Field(default_factory=lambda: BudgetBreakdown(
        flights=0, stay=0, activities=0, food=0, total=0, currency="₹"
    ))
    cover_emoji: str = Field(default="✈️")
    verification_tips: list[str] = Field(default_factory=list)

    # ── Server-injected fields (not generated by LLM) ─────────────────────────
    id: str = Field(default_factory=lambda: str(uuid4()))
    origin: str | None = None
    start_date: str | None = None
    end_date: str | None = None
    status: str = "planning"
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    hotel_options: list = Field(default_factory=list)
    flight_options: list = Field(default_factory=list)

    # ── WeatherAgent passthrough (injected from state, not re-generated) ──────
    daily_forecast: list[DailyForecast] = Field(default_factory=list)
    trip_risks: list[TripRisk] = Field(default_factory=list)
    requires_replanning: bool = False
    weather_summary: str | None = None
